name: 0.1$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  name: 'Default scale set'

variables:
  - group: amcsplatform_github
steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - powershell: |
      $BranchName = "$(Build.SourceBranch)" -Replace "refs/heads/", ""
      git tag v$(Build.BuildNumber)
      git push origin v$(Build.BuildNumber)
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git HEAD:$BranchName
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git v$(Build.BuildNumber)
    displayName: 'Push changes to GitHub'
