name: 0.1$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  name: 'Default scale set'

variables:
  - group: amcsplatform_github
  - group: customercontrol-dev
  - group: amcsdevops
steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - script: git config --global url."https://devops:$(credentials-devops-pat)@dev.azure.com/amcsgroup/DevOps/_git/CustomerControlClientGo".insteadOf "https://dev.azure.com/amcsgroup/DevOps/_git/CustomerControlClientGo"
    displayName: 'Git config'

  - task: GoTool@0
    displayName: 'Use Go 1.16'
    inputs:
      version: '1.16'

  - task: Go@0
    displayName: 'Go get'
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: make testacc
    displayName: 'Run integration tests'
    env:
      CUSTOMERCONTROL_URL: 'https://customercontrol-dev.amcsgroup.io'
      CUSTOMERCONTROL_PRIVATE_KEY: $(credentials-api-private-key)

  - powershell: |
      $BranchName = "$(Build.SourceBranch)" -Replace "refs/heads/", ""
      git tag v$(Build.BuildNumber)
      git push origin v$(Build.BuildNumber)
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git HEAD:$BranchName
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git v$(Build.BuildNumber)
    displayName: 'Push changes to GitHub'
