parameters:
  - name: pushToGitHub
    displayName: 'Push source to GitHub'
    type: boolean
    default: false

# Version is controlled in templates/variables.yml
name: $(majorMinorVersion).$(patchVersion)

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  name: 'Default scale set'
workspace:
  clean: all
variables:
  - template: templates/variables.yml
steps:
  - template: templates/base.yml

  - powershell: |
      $BranchName = "$(Build.SourceBranch)" -Replace "refs/heads/", ""
      $GitTag = "v$(Build.BuildNumber)"
      git tag $GitTag
      git push origin $GitTag
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git HEAD:$BranchName
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git $GitTag
    displayName: 'Push changes to GitHub'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(${{ parameters.pushToGitHub }}, true)))
