name: 0.1$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master

pool:
  name: 'Default scale set'

variables:
  - group: amcsplatform_github
  - name: CUSTOMERCONTROL_URL
    value: 'https://customercontrol-dev.amcsgroup.io'
  - name: CUSTOMERCONTROL_PRIVATE_KEY
    value: $(credentials-api-private-key)
steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: AzureKeyVault@1
    displayName: 'Get CustomerControl private key'
    inputs:
      azureSubscription: 'Development Subscription'
      keyVaultName: 'customercontrol-dev-kv'
      secretsFilter: 'credentials-api-private-key'
      runAsPreJob: true

  - task: GoTool@0
    inputs:
      version: '1.16'

  - task: Go@0
    displayName: 'Go get'
    inputs:
      command: 'get'
      arguments: '-d'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: make testacc

  - powershell: |
      $BranchName = "$(Build.SourceBranch)" -Replace "refs/heads/", ""
      git tag v$(Build.BuildNumber)
      git push origin v$(Build.BuildNumber)
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git HEAD:$BranchName
      git push https://anything:$(github_pat)@github.com/amcsplatform/terraform-provider-customercontrol.git v$(Build.BuildNumber)
    displayName: 'Push changes to GitHub'
